/**
 * Canonical merchants seed data for Malaysia (MY), Indonesia (ID), Thailand (TH).
 * Same format as TR: 100 popular merchants per country.
 * Use with: npx tsx scripts/generate-merchants-seed-multi.ts
 */

export type MerchantSeed = {
  canonicalName: string;
  displayName: string;
  category: string;
  tier: "verified" | "candidate" | "unverified";
  patterns: string[];
};

/** Normalize for pattern matching (Latin/ASCII). */
export function normalizeLatin(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^\w\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const c = "candidate" as const;

// Malaysia (MY) - 100 popular merchants
export const MY_MERCHANTS: MerchantSeed[] = [
  { canonicalName: "Giant Hypermarket", displayName: "Giant", category: "supermarket", tier: c, patterns: ["Giant", "GIANT", "Giant Hypermarket"] },
  { canonicalName: "AEON Malaysia", displayName: "AEON", category: "supermarket", tier: c, patterns: ["AEON", "Aeon", "AEON Big", "Jaya Grocer"] },
  { canonicalName: "Lotus's Malaysia", displayName: "Lotus's", category: "supermarket", tier: c, patterns: ["Lotus's", "Lotus", "LOTUS", "Tesco Malaysia"] },
  { canonicalName: "Mydin Malaysia", displayName: "Mydin", category: "supermarket", tier: c, patterns: ["Mydin", "MYDIN", "Mydin Wholesale"] },
  { canonicalName: "99 Speedmart", displayName: "99 Speedmart", category: "convenience", tier: c, patterns: ["99 Speedmart", "99 Speed Mart", "99Speedmart"] },
  { canonicalName: "7-Eleven Malaysia", displayName: "7-Eleven", category: "convenience", tier: c, patterns: ["7-Eleven", "7-Eleven Malaysia", "7ELEVEN"] },
  { canonicalName: "FamilyMart Malaysia", displayName: "FamilyMart", category: "convenience", tier: c, patterns: ["FamilyMart", "Family Mart", "FAMILYMART"] },
  { canonicalName: "MyNews Malaysia", displayName: "MyNews", category: "convenience", tier: c, patterns: ["MyNews", "My News", "MYNEWS"] },
  { canonicalName: "Guardian Malaysia", displayName: "Guardian", category: "pharmacy", tier: c, patterns: ["Guardian", "GUARDIAN"] },
  { canonicalName: "Watsons Malaysia", displayName: "Watsons", category: "pharmacy", tier: c, patterns: ["Watsons", "WATSONS", "Watson"] },
  { canonicalName: "Starbucks Malaysia", displayName: "Starbucks", category: "cafe", tier: c, patterns: ["Starbucks", "STARBUCKS"] },
  { canonicalName: "McDonald's Malaysia", displayName: "McDonald's", category: "restaurant", tier: c, patterns: ["McDonald's", "McDonalds", "MCDONALDS"] },
  { canonicalName: "KFC Malaysia", displayName: "KFC", category: "restaurant", tier: c, patterns: ["KFC", "Kentucky Fried Chicken"] },
  { canonicalName: "Shell Malaysia", displayName: "Shell", category: "fuel", tier: c, patterns: ["Shell", "SHELL"] },
  { canonicalName: "Petronas Malaysia", displayName: "Petronas", category: "fuel", tier: c, patterns: ["Petronas", "PETRONAS", "Petron"] },
  { canonicalName: "BHP Malaysia", displayName: "BHP", category: "fuel", tier: c, patterns: ["BHP", "BHP Petroleum"] },
  { canonicalName: "Caltex Malaysia", displayName: "Caltex", category: "fuel", tier: c, patterns: ["Caltex", "CALTEX"] },
  { canonicalName: "Parkson Malaysia", displayName: "Parkson", category: "supermarket", tier: c, patterns: ["Parkson", "PARKSON"] },
  { canonicalName: "Village Park Restaurant", displayName: "Village Park", category: "restaurant", tier: c, patterns: ["Village Park", "Village Park Restaurant"] },
  { canonicalName: "OldTown White Coffee", displayName: "OldTown", category: "cafe", tier: c, patterns: ["OldTown", "Old Town", "OLDTOWN"] },
  { canonicalName: "Secret Recipe Malaysia", displayName: "Secret Recipe", category: "restaurant", tier: c, patterns: ["Secret Recipe", "SecretRecipe"] },
  { canonicalName: "Tealive Malaysia", displayName: "Tealive", category: "cafe", tier: c, patterns: ["Tealive", "Tea Live", "TEALIVE"] },
  { canonicalName: "Chatime Malaysia", displayName: "Chatime", category: "cafe", tier: c, patterns: ["Chatime", "Cha Time", "CHATIME"] },
  { canonicalName: "Boost Malaysia", displayName: "Boost", category: "cafe", tier: c, patterns: ["Boost", "BOOST"] },
  { canonicalName: "Domino's Pizza Malaysia", displayName: "Domino's", category: "restaurant", tier: c, patterns: ["Domino's", "Dominos", "DOMINOS"] },
  { canonicalName: "Pizza Hut Malaysia", displayName: "Pizza Hut", category: "restaurant", tier: c, patterns: ["Pizza Hut", "PIZZA HUT"] },
  { canonicalName: "Subway Malaysia", displayName: "Subway", category: "restaurant", tier: c, patterns: ["Subway", "SUBWAY"] },
  { canonicalName: "Econsave Malaysia", displayName: "Econsave", category: "supermarket", tier: c, patterns: ["Econsave", "Econ Save", "ECONSAVE"] },
  { canonicalName: "Jaya Grocer", displayName: "Jaya Grocer", category: "supermarket", tier: c, patterns: ["Jaya Grocer", "Jaya Grocer"] },
  { canonicalName: "Village Grocer", displayName: "Village Grocer", category: "supermarket", tier: c, patterns: ["Village Grocer", "Village Grocer"] },
  { canonicalName: "Lazada Malaysia", displayName: "Lazada", category: "marketplace", tier: c, patterns: ["Lazada", "LAZADA"] },
  { canonicalName: "Shopee Malaysia", displayName: "Shopee", category: "marketplace", tier: c, patterns: ["Shopee", "SHOPEE"] },
  { canonicalName: "Grab Malaysia", displayName: "Grab", category: "marketplace", tier: c, patterns: ["Grab", "GRAB", "GrabFood"] },
  { canonicalName: "Foodpanda Malaysia", displayName: "Foodpanda", category: "marketplace", tier: c, patterns: ["Foodpanda", "Food Panda", "FOODPANDA"] },
  { canonicalName: "Senheng Malaysia", displayName: "Senheng", category: "electronics", tier: c, patterns: ["Senheng", "SENHENG"] },
  { canonicalName: "SenQ Malaysia", displayName: "SenQ", category: "electronics", tier: c, patterns: ["SenQ", "SENQ"] },
  { canonicalName: "Courts Malaysia", displayName: "Courts", category: "electronics", tier: c, patterns: ["Courts", "COURTS"] },
  { canonicalName: "Harvey Norman Malaysia", displayName: "Harvey Norman", category: "electronics", tier: c, patterns: ["Harvey Norman", "Harvey Norman"] },
  { canonicalName: "Uniqlo Malaysia", displayName: "Uniqlo", category: "apparel", tier: c, patterns: ["Uniqlo", "UNIQLO"] },
  { canonicalName: "H&M Malaysia", displayName: "H&M", category: "apparel", tier: c, patterns: ["H&M", "H and M", "HM"] },
  { canonicalName: "Padini Malaysia", displayName: "Padini", category: "apparel", tier: c, patterns: ["Padini", "PADINI"] },
  { canonicalName: "Vincci Malaysia", displayName: "Vincci", category: "apparel", tier: c, patterns: ["Vincci", "VINCCI"] },
  { canonicalName: "Sephora Malaysia", displayName: "Sephora", category: "beauty", tier: c, patterns: ["Sephora", "SEPHORA"] },
  { canonicalName: "Sasa Malaysia", displayName: "Sasa", category: "beauty", tier: c, patterns: ["Sasa", "SASA"] },
  { canonicalName: "BreadStory Malaysia", displayName: "BreadStory", category: "cafe", tier: c, patterns: ["BreadStory", "Bread Story"] },
  { canonicalName: "PappaRich Malaysia", displayName: "PappaRich", category: "restaurant", tier: c, patterns: ["PappaRich", "Pappa Rich", "PAPPARICH"] },
  { canonicalName: "Restaurant Kin Kin", displayName: "Kin Kin", category: "restaurant", tier: c, patterns: ["Kin Kin", "Kin Kin Restaurant"] },
  { canonicalName: "Nandos Malaysia", displayName: "Nando's", category: "restaurant", tier: c, patterns: ["Nando's", "Nandos", "NANDOS"] },
  { canonicalName: "Sushi King Malaysia", displayName: "Sushi King", category: "restaurant", tier: c, patterns: ["Sushi King", "Sushi King"] },
  { canonicalName: "Sakae Sushi Malaysia", displayName: "Sakae Sushi", category: "restaurant", tier: c, patterns: ["Sakae Sushi", "Sakae"] },
  { canonicalName: "Din Tai Fung Malaysia", displayName: "Din Tai Fung", category: "restaurant", tier: c, patterns: ["Din Tai Fung", "Din Tai Fung"] },
  { canonicalName: "Coffee Bean Malaysia", displayName: "Coffee Bean", category: "cafe", tier: c, patterns: ["Coffee Bean", "The Coffee Bean", "COFFEE BEAN"] },
  { canonicalName: "San Francisco Coffee", displayName: "San Francisco Coffee", category: "cafe", tier: c, patterns: ["San Francisco Coffee", "SF Coffee"] },
  { canonicalName: "Baskin Robbins Malaysia", displayName: "Baskin Robbins", category: "cafe", tier: c, patterns: ["Baskin Robbins", "Baskin Robbins"] },
  { canonicalName: "Burgertory Malaysia", displayName: "Burgertory", category: "restaurant", tier: c, patterns: ["Burgertory", "Burgertory"] },
  { canonicalName: "MyBurgerLab Malaysia", displayName: "MyBurgerLab", category: "restaurant", tier: c, patterns: ["MyBurgerLab", "My Burger Lab"] },
  { canonicalName: "Vivo Pizza Malaysia", displayName: "Vivo Pizza", category: "restaurant", tier: c, patterns: ["Vivo Pizza", "Vivo"] },
  { canonicalName: "Marrybrown Malaysia", displayName: "Marrybrown", category: "restaurant", tier: c, patterns: ["Marrybrown", "Marry Brown", "MARRYBROWN"] },
  { canonicalName: "A&W Malaysia", displayName: "A&W", category: "restaurant", tier: c, patterns: ["A&W", "A and W", "AW"] },
  { canonicalName: "Pizza Man Malaysia", displayName: "Pizza Man", category: "restaurant", tier: c, patterns: ["Pizza Man", "Pizza Man"] },
  { canonicalName: "Boat Noodle Malaysia", displayName: "Boat Noodle", category: "restaurant", tier: c, patterns: ["Boat Noodle", "Boat Noodle"] },
  { canonicalName: "Family Mart Malaysia", displayName: "Family Mart", category: "convenience", tier: c, patterns: ["Family Mart", "FamilyMart"] },
  { canonicalName: "KK Super Mart Malaysia", displayName: "KK Super Mart", category: "convenience", tier: c, patterns: ["KK Super Mart", "KK Mart", "KK SuperMart"] },
  { canonicalName: "Mamak Restaurant", displayName: "Mamak", category: "restaurant", tier: c, patterns: ["Mamak", "MAMAK"] },
  { canonicalName: "NSK Grocer", displayName: "NSK", category: "supermarket", tier: c, patterns: ["NSK", "NSK Grocer"] },
  { canonicalName: "The Store Malaysia", displayName: "The Store", category: "supermarket", tier: c, patterns: ["The Store", "The Store"] },
  { canonicalName: "Mydin Mall", displayName: "Mydin Mall", category: "supermarket", tier: c, patterns: ["Mydin Mall", "Mydin Mall"] },
  { canonicalName: "Hero Market Malaysia", displayName: "Hero", category: "supermarket", tier: c, patterns: ["Hero", "Hero Market"] },
  { canonicalName: "Pacific Coffee Malaysia", displayName: "Pacific Coffee", category: "cafe", tier: c, patterns: ["Pacific Coffee", "Pacific Coffee"] },
  { canonicalName: "Starbucks Reserve Malaysia", displayName: "Starbucks Reserve", category: "cafe", tier: c, patterns: ["Starbucks Reserve", "Starbucks Reserve"] },
  { canonicalName: "Zus Coffee Malaysia", displayName: "Zus Coffee", category: "cafe", tier: c, patterns: ["Zus Coffee", "Zus", "ZUS COFFEE"] },
  { canonicalName: "Billion Malaysia", displayName: "Billion", category: "supermarket", tier: c, patterns: ["Billion", "Billion Shopping"] },
  { canonicalName: "Mega Value Store", displayName: "Mega Value", category: "supermarket", tier: c, patterns: ["Mega Value", "Mega Value Store"] },
  { canonicalName: "TF Value-Mart", displayName: "TF Value-Mart", category: "supermarket", tier: c, patterns: ["TF Value-Mart", "TF Value Mart"] },
  { canonicalName: "MR.DIY Malaysia", displayName: "MR.DIY", category: "electronics", tier: c, patterns: ["MR.DIY", "MR DIY", "MRDiy"] },
  { canonicalName: "Daiso Malaysia", displayName: "Daiso", category: "electronics", tier: c, patterns: ["Daiso", "DAISO"] },
  { canonicalName: "Miniso Malaysia", displayName: "Miniso", category: "electronics", tier: c, patterns: ["Miniso", "MINISO"] },
  { canonicalName: "Samsung Malaysia", displayName: "Samsung", category: "electronics", tier: c, patterns: ["Samsung", "SAMSUNG"] },
  { canonicalName: "Apple Store Malaysia", displayName: "Apple", category: "electronics", tier: c, patterns: ["Apple", "Apple Store", "APPLE"] },
  { canonicalName: "Xiaomi Malaysia", displayName: "Xiaomi", category: "electronics", tier: c, patterns: ["Xiaomi", "XIAOMI"] },
  { canonicalName: "Huawei Malaysia", displayName: "Huawei", category: "electronics", tier: c, patterns: ["Huawei", "HUAWEI"] },
  { canonicalName: "OPPO Malaysia", displayName: "OPPO", category: "electronics", tier: c, patterns: ["OPPO", "Oppo"] },
  { canonicalName: "Vivo Malaysia", displayName: "Vivo", category: "electronics", tier: c, patterns: ["Vivo", "VIVO"] },
  { canonicalName: "Digi Malaysia", displayName: "Digi", category: "electronics", tier: c, patterns: ["Digi", "DIGI", "Digi Telecommunications"] },
  { canonicalName: "Maxis Malaysia", displayName: "Maxis", category: "electronics", tier: c, patterns: ["Maxis", "MAXIS"] },
  { canonicalName: "Celcom Malaysia", displayName: "Celcom", category: "electronics", tier: c, patterns: ["Celcom", "CELCOM"] },
  { canonicalName: "U Mobile Malaysia", displayName: "U Mobile", category: "electronics", tier: c, patterns: ["U Mobile", "U Mobile", "UMobile"] },
  { canonicalName: "Decathlon Malaysia", displayName: "Decathlon", category: "apparel", tier: c, patterns: ["Decathlon", "DECATHLON"] },
  { canonicalName: "Nike Malaysia", displayName: "Nike", category: "apparel", tier: c, patterns: ["Nike", "NIKE"] },
  { canonicalName: "Adidas Malaysia", displayName: "Adidas", category: "apparel", tier: c, patterns: ["Adidas", "ADIDAS"] },
  { canonicalName: "Puma Malaysia", displayName: "Puma", category: "apparel", tier: c, patterns: ["Puma", "PUMA"] },
  { canonicalName: "Skechers Malaysia", displayName: "Skechers", category: "apparel", tier: c, patterns: ["Skechers", "SKECHERS"] },
  { canonicalName: "Padini Holdings", displayName: "Padini Holdings", category: "apparel", tier: c, patterns: ["Padini Holdings", "Padini"] },
  { canonicalName: "Brands Outlet Malaysia", displayName: "Brands Outlet", category: "apparel", tier: c, patterns: ["Brands Outlet", "Brands Outlet"] },
  { canonicalName: "Aeon Co Malaysia", displayName: "Aeon Co", category: "supermarket", tier: c, patterns: ["Aeon Co", "AEON Co"] },
  { canonicalName: "Village Park Nasi Lemak", displayName: "Village Park Nasi Lemak", category: "restaurant", tier: c, patterns: ["Village Park Nasi Lemak"] },
  { canonicalName: "Restaurant Sri Nirwana", displayName: "Sri Nirwana", category: "restaurant", tier: c, patterns: ["Sri Nirwana", "Sri Nirwana Maju"] },
  { canonicalName: "Restaurant Rebung", displayName: "Rebung", category: "restaurant", tier: c, patterns: ["Rebung", "Rebung Restaurant"] },
  { canonicalName: "Madam Kwan Malaysia", displayName: "Madam Kwan", category: "restaurant", tier: c, patterns: ["Madam Kwan", "Madam Kwan's"] },
  { canonicalName: "Restaurant Antara", displayName: "Antara", category: "restaurant", tier: c, patterns: ["Antara", "Antara Restaurant"] },
  { canonicalName: "Bijan Bar and Restaurant", displayName: "Bijan", category: "restaurant", tier: c, patterns: ["Bijan", "Bijan Restaurant"] },
  { canonicalName: "Frontera Malaysia", displayName: "Frontera", category: "restaurant", tier: c, patterns: ["Frontera", "Frontera Grill"] },
  { canonicalName: "Tony Roma's Malaysia", displayName: "Tony Roma's", category: "restaurant", tier: c, patterns: ["Tony Roma's", "Tony Romas"] },
  { canonicalName: "TGI Friday's Malaysia", displayName: "TGI Friday's", category: "restaurant", tier: c, patterns: ["TGI Friday's", "TGIF", "TGI Fridays"] },
  { canonicalName: "Chili's Malaysia", displayName: "Chili's", category: "restaurant", tier: c, patterns: ["Chili's", "Chilis", "CHILIS"] },
  { canonicalName: "Sushi Zanmai Malaysia", displayName: "Sushi Zanmai", category: "restaurant", tier: c, patterns: ["Sushi Zanmai", "Sushi Zanmai"] },
  { canonicalName: "Rakuzen Malaysia", displayName: "Rakuzen", category: "restaurant", tier: c, patterns: ["Rakuzen", "Rakuzen"] },
  { canonicalName: "Ichiran Malaysia", displayName: "Ichiran", category: "restaurant", tier: c, patterns: ["Ichiran", "Ichiran Ramen"] },
  { canonicalName: "Hoshino Coffee Malaysia", displayName: "Hoshino Coffee", category: "cafe", tier: c, patterns: ["Hoshino Coffee", "Hoshino"] },
  { canonicalName: "Dome Cafe Malaysia", displayName: "Dome Cafe", category: "cafe", tier: c, patterns: ["Dome Cafe", "Dome", "DOME"] },
  { canonicalName: "Starbucks Drive-Thru", displayName: "Starbucks Drive-Thru", category: "cafe", tier: c, patterns: ["Starbucks Drive-Thru"] },
  { canonicalName: "Gong Cha Malaysia", displayName: "Gong Cha", category: "cafe", tier: c, patterns: ["Gong Cha", "GongCha", "GONG CHA"] },
  { canonicalName: "Tiger Sugar Malaysia", displayName: "Tiger Sugar", category: "cafe", tier: c, patterns: ["Tiger Sugar", "Tiger Sugar"] },
  { canonicalName: "Xing Fu Tang Malaysia", displayName: "Xing Fu Tang", category: "cafe", tier: c, patterns: ["Xing Fu Tang", "Xing Fu Tang"] },
  { canonicalName: "Daboba Malaysia", displayName: "Daboba", category: "cafe", tier: c, patterns: ["Daboba", "DABOBA"] },
  { canonicalName: "Tealive Signature", displayName: "Tealive Signature", category: "cafe", tier: c, patterns: ["Tealive Signature"] },
];

// Indonesia (ID) - 100 popular merchants
export const ID_MERCHANTS: MerchantSeed[] = [
  { canonicalName: "Indomaret", displayName: "Indomaret", category: "convenience", tier: c, patterns: ["Indomaret", "INDOMARET", "Indoaret"] },
  { canonicalName: "Alfamart", displayName: "Alfamart", category: "convenience", tier: c, patterns: ["Alfamart", "ALFAMART", "Alfa Mart"] },
  { canonicalName: "Alfamidi", displayName: "Alfamidi", category: "convenience", tier: c, patterns: ["Alfamidi", "ALFAMIDI", "Alfa Midi"] },
  { canonicalName: "Circle K Indonesia", displayName: "Circle K", category: "convenience", tier: c, patterns: ["Circle K", "CircleK", "CIRCLE K"] },
  { canonicalName: "Lawson Indonesia", displayName: "Lawson", category: "convenience", tier: c, patterns: ["Lawson", "LAWSON"] },
  { canonicalName: "FamilyMart Indonesia", displayName: "FamilyMart", category: "convenience", tier: c, patterns: ["FamilyMart", "Family Mart", "FAMILYMART"] },
  { canonicalName: "7-Eleven Indonesia", displayName: "7-Eleven", category: "convenience", tier: c, patterns: ["7-Eleven", "7-Eleven Indonesia", "7ELEVEN"] },
  { canonicalName: "Super Indo", displayName: "Super Indo", category: "supermarket", tier: c, patterns: ["Super Indo", "SuperIndo", "SUPER INDO"] },
  { canonicalName: "Hypermart Indonesia", displayName: "Hypermart", category: "supermarket", tier: c, patterns: ["Hypermart", "HYPERMART"] },
  { canonicalName: "Carrefour Indonesia", displayName: "Carrefour", category: "supermarket", tier: c, patterns: ["Carrefour", "CARREFOUR"] },
  { canonicalName: "Transmart Indonesia", displayName: "Transmart", category: "supermarket", tier: c, patterns: ["Transmart", "TRANSMART"] },
  { canonicalName: "Lotte Mart Indonesia", displayName: "Lotte Mart", category: "supermarket", tier: c, patterns: ["Lotte Mart", "LotteMart", "LOTTE MART"] },
  { canonicalName: "AEON Indonesia", displayName: "AEON", category: "supermarket", tier: c, patterns: ["AEON", "Aeon Indonesia"] },
  { canonicalName: "Ranch Market Indonesia", displayName: "Ranch Market", category: "supermarket", tier: c, patterns: ["Ranch Market", "Ranch Market"] },
  { canonicalName: "Hero Supermarket", displayName: "Hero", category: "supermarket", tier: c, patterns: ["Hero", "Hero Supermarket"] },
  { canonicalName: "Guardian Indonesia", displayName: "Guardian", category: "pharmacy", tier: c, patterns: ["Guardian", "GUARDIAN"] },
  { canonicalName: "Watsons Indonesia", displayName: "Watsons", category: "pharmacy", tier: c, patterns: ["Watsons", "WATSONS"] },
  { canonicalName: "KFC Indonesia", displayName: "KFC", category: "restaurant", tier: c, patterns: ["KFC", "Kentucky Fried Chicken"] },
  { canonicalName: "McDonald's Indonesia", displayName: "McDonald's", category: "restaurant", tier: c, patterns: ["McDonald's", "McDonalds", "MCDONALDS"] },
  { canonicalName: "Starbucks Indonesia", displayName: "Starbucks", category: "cafe", tier: c, patterns: ["Starbucks", "STARBUCKS"] },
  { canonicalName: "Shell Indonesia", displayName: "Shell", category: "fuel", tier: c, patterns: ["Shell", "SHELL"] },
  { canonicalName: "Pertamina Indonesia", displayName: "Pertamina", category: "fuel", tier: c, patterns: ["Pertamina", "PERTAMINA", "Pertamina Gas Station"] },
  { canonicalName: "BP Indonesia", displayName: "BP", category: "fuel", tier: c, patterns: ["BP", "BP Indonesia"] },
  { canonicalName: "Tokopedia", displayName: "Tokopedia", category: "marketplace", tier: c, patterns: ["Tokopedia", "TOKOPEDIA"] },
  { canonicalName: "Shopee Indonesia", displayName: "Shopee", category: "marketplace", tier: c, patterns: ["Shopee", "SHOPEE"] },
  { canonicalName: "Lazada Indonesia", displayName: "Lazada", category: "marketplace", tier: c, patterns: ["Lazada", "LAZADA"] },
  { canonicalName: "Bukalapak", displayName: "Bukalapak", category: "marketplace", tier: c, patterns: ["Bukalapak", "BUKALAPAK"] },
  { canonicalName: "Blibli Indonesia", displayName: "Blibli", category: "marketplace", tier: c, patterns: ["Blibli", "BLIBLI"] },
  { canonicalName: "Gojek Indonesia", displayName: "Gojek", category: "marketplace", tier: c, patterns: ["Gojek", "GOJEK", "GoFood"] },
  { canonicalName: "Grab Indonesia", displayName: "Grab", category: "marketplace", tier: c, patterns: ["Grab", "GRAB", "GrabFood"] },
  { canonicalName: "Kopi Kenangan", displayName: "Kopi Kenangan", category: "cafe", tier: c, patterns: ["Kopi Kenangan", "Kopi Kenangan"] },
  { canonicalName: "Janji Jiwa", displayName: "Janji Jiwa", category: "cafe", tier: c, patterns: ["Janji Jiwa", "Janji Jiwa"] },
  { canonicalName: "Fore Coffee", displayName: "Fore Coffee", category: "cafe", tier: c, patterns: ["Fore Coffee", "Fore Coffee"] },
  { canonicalName: "Starbucks Reserve Indonesia", displayName: "Starbucks Reserve", category: "cafe", tier: c, patterns: ["Starbucks Reserve"] },
  { canonicalName: "J.CO Donuts Indonesia", displayName: "J.CO Donuts", category: "cafe", tier: c, patterns: ["J.CO Donuts", "JCO", "J Co Donuts"] },
  { canonicalName: "Krispy Kreme Indonesia", displayName: "Krispy Kreme", category: "cafe", tier: c, patterns: ["Krispy Kreme", "Krispy Kreme"] },
  { canonicalName: "Pizza Hut Indonesia", displayName: "Pizza Hut", category: "restaurant", tier: c, patterns: ["Pizza Hut", "PIZZA HUT"] },
  { canonicalName: "Domino's Pizza Indonesia", displayName: "Domino's", category: "restaurant", tier: c, patterns: ["Domino's", "Dominos", "DOMINOS"] },
  { canonicalName: "HokBen Indonesia", displayName: "HokBen", category: "restaurant", tier: c, patterns: ["HokBen", "HokBen", "HOKBEN"] },
  { canonicalName: "Yoshinoya Indonesia", displayName: "Yoshinoya", category: "restaurant", tier: c, patterns: ["Yoshinoya", "YOSHINOYA"] },
  { canonicalName: "Sukiya Indonesia", displayName: "Sukiya", category: "restaurant", tier: c, patterns: ["Sukiya", "SUKIYA"] },
  { canonicalName: "Marugame Udon Indonesia", displayName: "Marugame Udon", category: "restaurant", tier: c, patterns: ["Marugame Udon", "Marugame"] },
  { canonicalName: "Es Teler 77", displayName: "Es Teler 77", category: "restaurant", tier: c, patterns: ["Es Teler 77", "Es Teler 77"] },
  { canonicalName: "Bakmi GM", displayName: "Bakmi GM", category: "restaurant", tier: c, patterns: ["Bakmi GM", "Bakmi GM"] },
  { canonicalName: "Solaria Indonesia", displayName: "Solaria", category: "restaurant", tier: c, patterns: ["Solaria", "SOLARIA"] },
  { canonicalName: "Geprek Bensu", displayName: "Geprek Bensu", category: "restaurant", tier: c, patterns: ["Geprek Bensu", "Geprek Bensu"] },
  { canonicalName: "Rumah Makan Padang", displayName: "Rumah Makan Padang", category: "restaurant", tier: c, patterns: ["Rumah Makan Padang", "RM Padang"] },
  { canonicalName: "Warteg", displayName: "Warteg", category: "restaurant", tier: c, patterns: ["Warteg", "WARTEG"] },
  { canonicalName: "Ayam Geprek", displayName: "Ayam Geprek", category: "restaurant", tier: c, patterns: ["Ayam Geprek", "Ayam Geprek"] },
  { canonicalName: "Chatime Indonesia", displayName: "Chatime", category: "cafe", tier: c, patterns: ["Chatime", "Cha Time", "CHATIME"] },
  { canonicalName: "Kopi Luwak Indonesia", displayName: "Kopi Luwak", category: "cafe", tier: c, patterns: ["Kopi Luwak", "Kopi Luwak"] },
  { canonicalName: "Excelso Indonesia", displayName: "Excelso", category: "cafe", tier: c, patterns: ["Excelso", "EXCELSO"] },
  { canonicalName: "Otten Coffee", displayName: "Otten Coffee", category: "cafe", tier: c, patterns: ["Otten Coffee", "Otten Coffee"] },
  { canonicalName: "Gramedia Indonesia", displayName: "Gramedia", category: "electronics", tier: c, patterns: ["Gramedia", "GRAMEDIA"] },
  { canonicalName: "Electronic City Indonesia", displayName: "Electronic City", category: "electronics", tier: c, patterns: ["Electronic City", "Electronic City"] },
  { canonicalName: "Tokopedia Official Store", displayName: "Tokopedia Store", category: "marketplace", tier: c, patterns: ["Tokopedia Store"] },
  { canonicalName: "Blibli Mall", displayName: "Blibli Mall", category: "marketplace", tier: c, patterns: ["Blibli Mall"] },
  { canonicalName: "Dan+Dan Indonesia", displayName: "Dan+Dan", category: "convenience", tier: c, patterns: ["Dan+Dan", "Dan Dan"] },
  { canonicalName: "Indomaret Point", displayName: "Indomaret Point", category: "convenience", tier: c, patterns: ["Indomaret Point"] },
  { canonicalName: "Alfamart Super", displayName: "Alfamart Super", category: "convenience", tier: c, patterns: ["Alfamart Super"] },
  { canonicalName: "Lotte Mart Super", displayName: "Lotte Mart Super", category: "supermarket", tier: c, patterns: ["Lotte Mart Super"] },
  { canonicalName: "Food Hall Indonesia", displayName: "Food Hall", category: "supermarket", tier: c, patterns: ["Food Hall", "Food Hall"] },
  { canonicalName: "Farmers Market Indonesia", displayName: "Farmers Market", category: "supermarket", tier: c, patterns: ["Farmers Market"] },
  { canonicalName: "Giant Indonesia", displayName: "Giant", category: "supermarket", tier: c, patterns: ["Giant", "GIANT Indonesia"] },
  { canonicalName: "Uniqlo Indonesia", displayName: "Uniqlo", category: "apparel", tier: c, patterns: ["Uniqlo", "UNIQLO"] },
  { canonicalName: "H&M Indonesia", displayName: "H&M", category: "apparel", tier: c, patterns: ["H&M", "H and M", "HM"] },
  { canonicalName: "Zara Indonesia", displayName: "Zara", category: "apparel", tier: c, patterns: ["Zara", "ZARA"] },
  { canonicalName: "Sephora Indonesia", displayName: "Sephora", category: "beauty", tier: c, patterns: ["Sephora", "SEPHORA"] },
  { canonicalName: "Samsung Indonesia", displayName: "Samsung", category: "electronics", tier: c, patterns: ["Samsung", "SAMSUNG"] },
  { canonicalName: "OPPO Indonesia", displayName: "OPPO", category: "electronics", tier: c, patterns: ["OPPO", "Oppo"] },
  { canonicalName: "Vivo Indonesia", displayName: "Vivo", category: "electronics", tier: c, patterns: ["Vivo", "VIVO"] },
  { canonicalName: "Xiaomi Indonesia", displayName: "Xiaomi", category: "electronics", tier: c, patterns: ["Xiaomi", "XIAOMI"] },
  { canonicalName: "Telkomsel Indonesia", displayName: "Telkomsel", category: "electronics", tier: c, patterns: ["Telkomsel", "TELKOMSEL"] },
  { canonicalName: "Indosat Ooredoo", displayName: "Indosat", category: "electronics", tier: c, patterns: ["Indosat", "INDOSAT", "IM3"] },
  { canonicalName: "XL Axiata", displayName: "XL Axiata", category: "electronics", tier: c, patterns: ["XL Axiata", "XL", "XL Axiata"] },
  { canonicalName: "Three Indonesia", displayName: "3 Indonesia", category: "electronics", tier: c, patterns: ["3 Indonesia", "Tri", "3"] },
  { canonicalName: "Pertamina Lubricants", displayName: "Pertamina Lubricants", category: "fuel", tier: c, patterns: ["Pertamina Lubricants"] },
  { canonicalName: "Total Indonesia", displayName: "Total", category: "fuel", tier: c, patterns: ["Total", "TOTAL Indonesia"] },
  { canonicalName: "Chevron Indonesia", displayName: "Chevron", category: "fuel", tier: c, patterns: ["Chevron", "CHEVRON"] },
  { canonicalName: "Vivo Plaza Indonesia", displayName: "Vivo Plaza", category: "electronics", tier: c, patterns: ["Vivo Plaza"] },
  { canonicalName: "iBox Indonesia", displayName: "iBox", category: "electronics", tier: c, patterns: ["iBox", "iBox Indonesia"] },
  { canonicalName: "Erafone Indonesia", displayName: "Erafone", category: "electronics", tier: c, patterns: ["Erafone", "ERAFONE"] },
  { canonicalName: "Matahari Department Store", displayName: "Matahari", category: "apparel", tier: c, patterns: ["Matahari", "MATAHARI"] },
  { canonicalName: "Central Department Store Indonesia", displayName: "Central", category: "apparel", tier: c, patterns: ["Central", "Central Department"] },
  { canonicalName: "Sogo Indonesia", displayName: "Sogo", category: "apparel", tier: c, patterns: ["Sogo", "SOGO"] },
  { canonicalName: "Metro Department Store", displayName: "Metro", category: "apparel", tier: c, patterns: ["Metro", "Metro Department"] },
  { canonicalName: "Ace Hardware Indonesia", displayName: "Ace Hardware", category: "electronics", tier: c, patterns: ["Ace Hardware", "Ace Hardware"] },
  { canonicalName: "Informa Indonesia", displayName: "Informa", category: "electronics", tier: c, patterns: ["Informa", "INFORMA"] },
  { canonicalName: "IKEA Indonesia", displayName: "IKEA", category: "electronics", tier: c, patterns: ["IKEA", "Ikea Indonesia"] },
  { canonicalName: "Informa Elektronik", displayName: "Informa Elektronik", category: "electronics", tier: c, patterns: ["Informa Elektronik"] },
  { canonicalName: "BreadTalk Indonesia", displayName: "BreadTalk", category: "cafe", tier: c, patterns: ["BreadTalk", "Bread Talk", "BREADTALK"] },
  { canonicalName: "Paris Baguette Indonesia", displayName: "Paris Baguette", category: "cafe", tier: c, patterns: ["Paris Baguette", "Paris Baguette"] },
  { canonicalName: "Starbucks Coffee Indonesia", displayName: "Starbucks Coffee", category: "cafe", tier: c, patterns: ["Starbucks Coffee"] },
  { canonicalName: "J.CO Donuts & Coffee", displayName: "J.CO", category: "cafe", tier: c, patterns: ["J.CO", "JCO Donuts"] },
  { canonicalName: "Kopi Oey", displayName: "Kopi Oey", category: "cafe", tier: c, patterns: ["Kopi Oey", "Kopi Oey"] },
  { canonicalName: "Warung Padang", displayName: "Warung Padang", category: "restaurant", tier: c, patterns: ["Warung Padang"] },
  { canonicalName: "Bebek Bengil Indonesia", displayName: "Bebek Bengil", category: "restaurant", tier: c, patterns: ["Bebek Bengil", "Bebek Bengil"] },
  { canonicalName: "Naughty Nuri's Indonesia", displayName: "Naughty Nuri's", category: "restaurant", tier: c, patterns: ["Naughty Nuri's", "Naughty Nuri"] },
  { canonicalName: "Sederhana Bintaro", displayName: "Sederhana", category: "restaurant", tier: c, patterns: ["Sederhana", "Sederhana Restaurant"] },
  { canonicalName: "Bakso Boedjangan", displayName: "Bakso Boedjangan", category: "restaurant", tier: c, patterns: ["Bakso Boedjangan"] },
  { canonicalName: "Martabak Orins", displayName: "Martabak Orins", category: "restaurant", tier: c, patterns: ["Martabak Orins", "Martabak Orins"] },
  { canonicalName: "Papa Ron's Pizza", displayName: "Papa Ron's", category: "restaurant", tier: c, patterns: ["Papa Ron's", "Papa Rons"] },
  { canonicalName: "Seribu Rasa", displayName: "Seribu Rasa", category: "restaurant", tier: c, patterns: ["Seribu Rasa", "Seribu Rasa"] },
  { canonicalName: "D'Cost Indonesia", displayName: "D'Cost", category: "restaurant", tier: c, patterns: ["D'Cost", "DCost", "D Cost"] },
  { canonicalName: "HokBen Delivery", displayName: "HokBen Delivery", category: "restaurant", tier: c, patterns: ["HokBen Delivery"] },
  { canonicalName: "Yoshinoya Delivery", displayName: "Yoshinoya Delivery", category: "restaurant", tier: c, patterns: ["Yoshinoya Delivery"] },
  { canonicalName: "KFC Delivery Indonesia", displayName: "KFC Delivery", category: "restaurant", tier: c, patterns: ["KFC Delivery"] },
  { canonicalName: "McDonald's Delivery", displayName: "McDonald's Delivery", category: "restaurant", tier: c, patterns: ["McDonald's Delivery"] },
  { canonicalName: "GoFood Merchant", displayName: "GoFood", category: "marketplace", tier: c, patterns: ["GoFood", "Go Food"] },
  { canonicalName: "GrabFood Merchant", displayName: "GrabFood", category: "marketplace", tier: c, patterns: ["GrabFood", "Grab Food"] },
  { canonicalName: "ShopeeFood Indonesia", displayName: "ShopeeFood", category: "marketplace", tier: c, patterns: ["ShopeeFood", "Shopee Food"] },
];

// Thailand (TH) - 100 popular merchants
export const TH_MERCHANTS: MerchantSeed[] = [
  { canonicalName: "7-Eleven Thailand", displayName: "7-Eleven", category: "convenience", tier: c, patterns: ["7-Eleven", "7-Eleven Thailand", "7ELEVEN"] },
  { canonicalName: "Lotus's Thailand", displayName: "Lotus's", category: "supermarket", tier: c, patterns: ["Lotus's", "Lotus", "LOTUS", "Tesco Lotus"] },
  { canonicalName: "Big C Thailand", displayName: "Big C", category: "supermarket", tier: c, patterns: ["Big C", "BigC", "BIG C"] },
  { canonicalName: "CP All Thailand", displayName: "CP All", category: "convenience", tier: c, patterns: ["CP All", "CP All"] },
  { canonicalName: "Makro Thailand", displayName: "Makro", category: "supermarket", tier: c, patterns: ["Makro", "MAKRO"] },
  { canonicalName: "Tops Thailand", displayName: "Tops", category: "supermarket", tier: c, patterns: ["Tops", "TOPS", "Tops Daily"] },
  { canonicalName: "FamilyMart Thailand", displayName: "FamilyMart", category: "convenience", tier: c, patterns: ["FamilyMart", "Family Mart", "FAMILYMART"] },
  { canonicalName: "Lawson 108 Thailand", displayName: "Lawson 108", category: "convenience", tier: c, patterns: ["Lawson 108", "Lawson108"] },
  { canonicalName: "Mini Big C", displayName: "Mini Big C", category: "convenience", tier: c, patterns: ["Mini Big C", "Mini Big C"] },
  { canonicalName: "Starbucks Thailand", displayName: "Starbucks", category: "cafe", tier: c, patterns: ["Starbucks", "STARBUCKS"] },
  { canonicalName: "McDonald's Thailand", displayName: "McDonald's", category: "restaurant", tier: c, patterns: ["McDonald's", "McDonalds", "MCDONALDS"] },
  { canonicalName: "KFC Thailand", displayName: "KFC", category: "restaurant", tier: c, patterns: ["KFC", "Kentucky Fried Chicken"] },
  { canonicalName: "Shell Thailand", displayName: "Shell", category: "fuel", tier: c, patterns: ["Shell", "SHELL"] },
  { canonicalName: "PTT Thailand", displayName: "PTT", category: "fuel", tier: c, patterns: ["PTT", "PTT Station", "PTT Oil"] },
  { canonicalName: "Bangchak Thailand", displayName: "Bangchak", category: "fuel", tier: c, patterns: ["Bangchak", "BANGCHAK"] },
  { canonicalName: "Caltex Thailand", displayName: "Caltex", category: "fuel", tier: c, patterns: ["Caltex", "CALTEX"] },
  { canonicalName: "Lazada Thailand", displayName: "Lazada", category: "marketplace", tier: c, patterns: ["Lazada", "LAZADA"] },
  { canonicalName: "Shopee Thailand", displayName: "Shopee", category: "marketplace", tier: c, patterns: ["Shopee", "SHOPEE"] },
  { canonicalName: "Grab Thailand", displayName: "Grab", category: "marketplace", tier: c, patterns: ["Grab", "GRAB", "GrabFood"] },
  { canonicalName: "Foodpanda Thailand", displayName: "Foodpanda", category: "marketplace", tier: c, patterns: ["Foodpanda", "Food Panda", "FOODPANDA"] },
  { canonicalName: "Line Man Thailand", displayName: "Line Man", category: "marketplace", tier: c, patterns: ["Line Man", "LineMan", "LINE MAN"] },
  { canonicalName: "True Coffee Thailand", displayName: "True Coffee", category: "cafe", tier: c, patterns: ["True Coffee", "True Coffee"] },
  { canonicalName: "Amazon Cafe Thailand", displayName: "Amazon Cafe", category: "cafe", tier: c, patterns: ["Amazon Cafe", "Amazon Cafe"] },
  { canonicalName: "Cafe Amazon", displayName: "Cafe Amazon", category: "cafe", tier: c, patterns: ["Cafe Amazon", "Cafe Amazon"] },
  { canonicalName: "Black Canyon Thailand", displayName: "Black Canyon", category: "cafe", tier: c, patterns: ["Black Canyon", "Black Canyon"] },
  { canonicalName: "Pizza Hut Thailand", displayName: "Pizza Hut", category: "restaurant", tier: c, patterns: ["Pizza Hut", "PIZZA HUT"] },
  { canonicalName: "Domino's Pizza Thailand", displayName: "Domino's", category: "restaurant", tier: c, patterns: ["Domino's", "Dominos", "DOMINOS"] },
  { canonicalName: "Subway Thailand", displayName: "Subway", category: "restaurant", tier: c, patterns: ["Subway", "SUBWAY"] },
  { canonicalName: "Swensen's Thailand", displayName: "Swensen's", category: "restaurant", tier: c, patterns: ["Swensen's", "Swensens", "SWENSENS"] },
  { canonicalName: "MK Restaurant Thailand", displayName: "MK Restaurant", category: "restaurant", tier: c, patterns: ["MK Restaurant", "MK", "MK Restaurants"] },
  { canonicalName: "Yayoi Thailand", displayName: "Yayoi", category: "restaurant", tier: c, patterns: ["Yayoi", "YAYOI"] },
  { canonicalName: "Fuji Restaurant Thailand", displayName: "Fuji", category: "restaurant", tier: c, patterns: ["Fuji", "Fuji Restaurant"] },
  { canonicalName: "Ootoya Thailand", displayName: "Ootoya", category: "restaurant", tier: c, patterns: ["Ootoya", "OOTOVA"] },
  { canonicalName: "Yoshinoya Thailand", displayName: "Yoshinoya", category: "restaurant", tier: c, patterns: ["Yoshinoya", "YOSHINOYA"] },
  { canonicalName: "Sukiya Thailand", displayName: "Sukiya", category: "restaurant", tier: c, patterns: ["Sukiya", "SUKIYA"] },
  { canonicalName: "Din Tai Fung Thailand", displayName: "Din Tai Fung", category: "restaurant", tier: c, patterns: ["Din Tai Fung", "Din Tai Fung"] },
  { canonicalName: "Foodland Thailand", displayName: "Foodland", category: "supermarket", tier: c, patterns: ["Foodland", "FOODLAND"] },
  { canonicalName: "Villa Market Thailand", displayName: "Villa Market", category: "supermarket", tier: c, patterns: ["Villa Market", "Villa Market"] },
  { canonicalName: "Gourmet Market Thailand", displayName: "Gourmet Market", category: "supermarket", tier: c, patterns: ["Gourmet Market", "Gourmet Market"] },
  { canonicalName: "MaxValu Thailand", displayName: "MaxValu", category: "supermarket", tier: c, patterns: ["MaxValu", "Max Valu", "MAXVALU"] },
  { canonicalName: "Jiffy Thailand", displayName: "Jiffy", category: "convenience", tier: c, patterns: ["Jiffy", "JIFFY"] },
  { canonicalName: "CJ Express Thailand", displayName: "CJ Express", category: "convenience", tier: c, patterns: ["CJ Express", "CJ Express"] },
  { canonicalName: "Watsons Thailand", displayName: "Watsons", category: "pharmacy", tier: c, patterns: ["Watsons", "WATSONS"] },
  { canonicalName: "Boots Thailand", displayName: "Boots", category: "pharmacy", tier: c, patterns: ["Boots", "BOOTS"] },
  { canonicalName: "Guardian Thailand", displayName: "Guardian", category: "pharmacy", tier: c, patterns: ["Guardian", "GUARDIAN"] },
  { canonicalName: "Uniqlo Thailand", displayName: "Uniqlo", category: "apparel", tier: c, patterns: ["Uniqlo", "UNIQLO"] },
  { canonicalName: "H&M Thailand", displayName: "H&M", category: "apparel", tier: c, patterns: ["H&M", "H and M", "HM"] },
  { canonicalName: "Zara Thailand", displayName: "Zara", category: "apparel", tier: c, patterns: ["Zara", "ZARA"] },
  { canonicalName: "Central Thailand", displayName: "Central", category: "apparel", tier: c, patterns: ["Central", "Central Department Store"] },
  { canonicalName: "Robinson Thailand", displayName: "Robinson", category: "apparel", tier: c, patterns: ["Robinson", "ROBINSON"] },
  { canonicalName: "The Mall Thailand", displayName: "The Mall", category: "apparel", tier: c, patterns: ["The Mall", "The Mall Group"] },
  { canonicalName: "Sephora Thailand", displayName: "Sephora", category: "beauty", tier: c, patterns: ["Sephora", "SEPHORA"] },
  { canonicalName: "Power Buy Thailand", displayName: "Power Buy", category: "electronics", tier: c, patterns: ["Power Buy", "Power Buy"] },
  { canonicalName: "Banana IT Thailand", displayName: "Banana IT", category: "electronics", tier: c, patterns: ["Banana IT", "Banana IT"] },
  { canonicalName: "Studio 7 Thailand", displayName: "Studio 7", category: "electronics", tier: c, patterns: ["Studio 7", "Studio 7"] },
  { canonicalName: "Samsung Thailand", displayName: "Samsung", category: "electronics", tier: c, patterns: ["Samsung", "SAMSUNG"] },
  { canonicalName: "Apple Store Thailand", displayName: "Apple", category: "electronics", tier: c, patterns: ["Apple", "Apple Store", "APPLE"] },
  { canonicalName: "OPPO Thailand", displayName: "OPPO", category: "electronics", tier: c, patterns: ["OPPO", "Oppo"] },
  { canonicalName: "Vivo Thailand", displayName: "Vivo", category: "electronics", tier: c, patterns: ["Vivo", "VIVO"] },
  { canonicalName: "Xiaomi Thailand", displayName: "Xiaomi", category: "electronics", tier: c, patterns: ["Xiaomi", "XIAOMI"] },
  { canonicalName: "Huawei Thailand", displayName: "Huawei", category: "electronics", tier: c, patterns: ["Huawei", "HUAWEI"] },
  { canonicalName: "AIS Thailand", displayName: "AIS", category: "electronics", tier: c, patterns: ["AIS", "Advanced Info Service"] },
  { canonicalName: "TrueMove Thailand", displayName: "TrueMove", category: "electronics", tier: c, patterns: ["TrueMove", "True Move", "TrueMove H"] },
  { canonicalName: "dtac Thailand", displayName: "dtac", category: "electronics", tier: c, patterns: ["dtac", "DTAC"] },
  { canonicalName: "IKEA Thailand", displayName: "IKEA", category: "electronics", tier: c, patterns: ["IKEA", "Ikea Thailand"] },
  { canonicalName: "HomePro Thailand", displayName: "HomePro", category: "electronics", tier: c, patterns: ["HomePro", "Home Pro", "HOMEPRO"] },
  { canonicalName: "Do Home Thailand", displayName: "Do Home", category: "electronics", tier: c, patterns: ["Do Home", "Do Home"] },
  { canonicalName: "B2S Thailand", displayName: "B2S", category: "electronics", tier: c, patterns: ["B2S", "B2S Thailand"] },
  { canonicalName: "Watsons Thailand", displayName: "Watsons", category: "pharmacy", tier: c, patterns: ["Watsons", "WATSONS"] },
  { canonicalName: "After You Thailand", displayName: "After You", category: "cafe", tier: c, patterns: ["After You", "After You"] },
  { canonicalName: "Audrey Cafe Thailand", displayName: "Audrey Cafe", category: "cafe", tier: c, patterns: ["Audrey Cafe", "Audrey Cafe"] },
  { canonicalName: "Greyhound Cafe Thailand", displayName: "Greyhound Cafe", category: "cafe", tier: c, patterns: ["Greyhound Cafe", "Greyhound Cafe"] },
  { canonicalName: "Cafe Kaldi Thailand", displayName: "Cafe Kaldi", category: "cafe", tier: c, patterns: ["Cafe Kaldi", "Cafe Kaldi"] },
  { canonicalName: "Inthanin Thailand", displayName: "Inthanin", category: "cafe", tier: c, patterns: ["Inthanin", "Inthanin Coffee"] },
  { canonicalName: "Doi Chaang Thailand", displayName: "Doi Chaang", category: "cafe", tier: c, patterns: ["Doi Chaang", "Doi Chaang Coffee"] },
  { canonicalName: "Pang Cha Thailand", displayName: "Pang Cha", category: "cafe", tier: c, patterns: ["Pang Cha", "Pang Cha"] },
  { canonicalName: "Cha Tra Mue Thailand", displayName: "Cha Tra Mue", category: "cafe", tier: c, patterns: ["Cha Tra Mue", "Cha Tra Mue"] },
  { canonicalName: "KFC Thailand Delivery", displayName: "KFC Delivery", category: "restaurant", tier: c, patterns: ["KFC Delivery"] },
  { canonicalName: "McDonald's Thailand Delivery", displayName: "McDonald's Delivery", category: "restaurant", tier: c, patterns: ["McDonald's Delivery"] },
  { canonicalName: "Pizza Company Thailand", displayName: "Pizza Company", category: "restaurant", tier: c, patterns: ["Pizza Company", "Pizza Company"] },
  { canonicalName: "Chester's Thailand", displayName: "Chester's", category: "restaurant", tier: c, patterns: ["Chester's", "Chester's Grill"] },
  { canonicalName: "Oishi Thailand", displayName: "Oishi", category: "restaurant", tier: c, patterns: ["Oishi", "OISHI"] },
  { canonicalName: "Shabushi Thailand", displayName: "Shabushi", category: "restaurant", tier: c, patterns: ["Shabushi", "Shabushi"] },
  { canonicalName: "Zen Japan Thailand", displayName: "Zen", category: "restaurant", tier: c, patterns: ["Zen", "Zen Japan"] },
  { canonicalName: "S&P Thailand", displayName: "S&P", category: "restaurant", tier: c, patterns: ["S&P", "S and P", "S&P Restaurant"] },
  { canonicalName: "Bonchon Thailand", displayName: "Bonchon", category: "restaurant", tier: c, patterns: ["Bonchon", "BONCHON"] },
  { canonicalName: "Papa John's Thailand", displayName: "Papa John's", category: "restaurant", tier: c, patterns: ["Papa John's", "Papa Johns"] },
  { canonicalName: "The Pizza Company", displayName: "The Pizza Company", category: "restaurant", tier: c, patterns: ["The Pizza Company"] },
  { canonicalName: "Mango Tree Thailand", displayName: "Mango Tree", category: "restaurant", tier: c, patterns: ["Mango Tree", "Mango Tree"] },
  { canonicalName: "Coca Thailand", displayName: "Coca", category: "restaurant", tier: c, patterns: ["Coca", "Coca Suki"] },
  { canonicalName: "MK Gold Thailand", displayName: "MK Gold", category: "restaurant", tier: c, patterns: ["MK Gold", "MK Gold"] },
  { canonicalName: "Lotus's Go Fresh", displayName: "Lotus's Go Fresh", category: "convenience", tier: c, patterns: ["Lotus's Go Fresh", "Go Fresh"] },
  { canonicalName: "Big C Supercenter", displayName: "Big C Supercenter", category: "supermarket", tier: c, patterns: ["Big C Supercenter"] },
  { canonicalName: "Tops Market Thailand", displayName: "Tops Market", category: "supermarket", tier: c, patterns: ["Tops Market"] },
  { canonicalName: "Villa Supermarket", displayName: "Villa Supermarket", category: "supermarket", tier: c, patterns: ["Villa Supermarket"] },
  { canonicalName: "Rimping Thailand", displayName: "Rimping", category: "supermarket", tier: c, patterns: ["Rimping", "Rimping Supermarket"] },
  { canonicalName: "Tops Daily Thailand", displayName: "Tops Daily", category: "convenience", tier: c, patterns: ["Tops Daily", "Tops Daily"] },
  { canonicalName: "CP Fresh Mart", displayName: "CP Fresh Mart", category: "convenience", tier: c, patterns: ["CP Fresh Mart", "CP Fresh Mart"] },
  { canonicalName: "PTT Station Cafe", displayName: "PTT Station Cafe", category: "cafe", tier: c, patterns: ["PTT Station Cafe"] },
  { canonicalName: "Lazada Express Thailand", displayName: "Lazada Express", category: "marketplace", tier: c, patterns: ["Lazada Express"] },
  { canonicalName: "Shopee Express Thailand", displayName: "Shopee Express", category: "marketplace", tier: c, patterns: ["Shopee Express"] },
];
